/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p66.tiendaropa_66.vista;

import p66.tiendaropa_66.conexion.SqliteConnection;
import p66.tiendaropa_66.controlador.ControladorCliente;
import p66.tiendaropa_66.modelo.Cliente;

/**
 *
 * @author Camilo A
 */
public class VentanaNuevoCliente extends javax.swing.JFrame {

        /**
         * Creates new form VentanaNuevoCliente
         */

        private SqliteConnection conexionBD;

        public VentanaNuevoCliente(SqliteConnection conexionBD) {
                initComponents();
                this.conexionBD = conexionBD;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtIdentificacion = new javax.swing.JTextField();
                txtNombres = new javax.swing.JTextField();
                txtApellidos = new javax.swing.JTextField();
                btnRegistrar = new javax.swing.JButton();
                btnCancelarn1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Registro de clientes");

                jLabel1.setText("Ingrese por favor los datos del cliente");

                jLabel2.setText("Identificación");

                jLabel3.setText("Nombres");

                jLabel4.setText("Apellidos");

                btnRegistrar.setText("Registrar");
                btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistrarActionPerformed(evt);
                        }
                });

                btnCancelarn1.setText("Cancelar");
                btnCancelarn1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarn1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(37, 37, 37)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(jLabel4))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false).addComponent(txtIdentificacion)
                                                                                .addComponent(txtNombres)
                                                                                .addComponent(txtApellidos,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                169, Short.MAX_VALUE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(82, 82, 82)
                                                                .addComponent(btnRegistrar).addGap(65, 65, 65)
                                                                .addComponent(btnCancelarn1)))
                                                .addContainerGap(26, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(27, 27, 27).addComponent(jLabel1)
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel2).addComponent(txtIdentificacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3).addComponent(txtNombres,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel4).addComponent(txtApellidos,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnRegistrar).addComponent(btnCancelarn1))
                                                .addGap(38, 38, 38)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCancelarn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarn1ActionPerformed
                this.dispose();
        }// GEN-LAST:event_btnCancelarn1ActionPerformed

        private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarActionPerformed
                String identificacion = txtIdentificacion.getText();
                String nombres = txtNombres.getText();
                String apellidos = txtApellidos.getText();
                ControladorCliente ctrlCliente = new ControladorCliente();

                Cliente nuevoCliente = new Cliente(identificacion, nombres, apellidos);
                ctrlCliente.crearCliente(nuevoCliente, conexionBD);

                txtIdentificacion.setText("");
                txtNombres.setText("");
                txtApellidos.setText("");
        }// GEN-LAST:event_btnRegistrarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancelarn1;
        private javax.swing.JButton btnRegistrar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField txtApellidos;
        private javax.swing.JTextField txtIdentificacion;
        private javax.swing.JTextField txtNombres;
        // End of variables declaration//GEN-END:variables
}