/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p66.tiendaropa_66.vista;

import p66.tiendaropa_66.conexion.SqliteConnection;

/**
 *
 */
public class VentanaMenu extends javax.swing.JFrame {

        private SqliteConnection conexionBD;

        /**
         * Creates new form VentanaMenu
         */
        public VentanaMenu(SqliteConnection conexionBD) {
                initComponents();
                this.conexionBD = conexionBD;
                String textoMenu = "Elija su opción: \n\n" + "1. Crear Cliente \n"
                                + "2. Listar diez primeros clientes \n" + "3. Listar productos comprados por cliente";
                tAreaMenu.setText(textoMenu);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tAreaMenu = new javax.swing.JTextArea();
                txtOpcion = new javax.swing.JTextField();
                btnSeleccionar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("La Tienda de Ropa - Sistema de información");

                jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(51, 0, 153));
                jLabel1.setText("La Tienda de Ropa");

                tAreaMenu.setEditable(false);
                tAreaMenu.setBackground(new java.awt.Color(240, 240, 240));
                tAreaMenu.setColumns(20);
                tAreaMenu.setLineWrap(true);
                tAreaMenu.setRows(5);
                tAreaMenu.setWrapStyleWord(true);
                jScrollPane1.setViewportView(tAreaMenu);

                btnSeleccionar.setText("Seleccionar");
                btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSeleccionarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                348,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(65, 65, 65)
                                                                .addComponent(txtOpcion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                83,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(72, 72, 72).addComponent(btnSeleccionar)))
                                                .addContainerGap(33, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(21, 21, 21).addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtOpcion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnSeleccionar))
                                                .addContainerGap(37, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSeleccionarActionPerformed
                String opcion = txtOpcion.getText();
                Menu opcionesMenu = new Menu();
                opcionesMenu.generarMenu(conexionBD, opcion);
        }// GEN-LAST:event_btnSeleccionarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnSeleccionar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea tAreaMenu;
        private javax.swing.JTextField txtOpcion;
        // End of variables declaration//GEN-END:variables
}